name: "✨ Feature Request"
description: Suggest an idea or enhancement for ProseFlow
title: "[FEAT] Brief description of the feature"
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Thank you for suggesting a feature! We appreciate your input.**

  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      options:
        - label: I have searched the existing issues to ensure this feature has not already been requested.
          required: true
        - label: I have clearly described the problem and the proposed solution.
          required: true
        - label: I have considered alternative solutions or workarounds.
          required: true

  - type: textarea
    id: problem-description
    attributes:
      label: 1. Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: |
        Example: I'm always frustrated when I create a new Action because I have to save it and run it in another app to see if the prompt works.
    validations:
      required: true

  - type: textarea
    id: desired-solution
    attributes:
      label: 2. Describe the Solution You'd Like
      description: |
        A clear and concise description of what you want to happen.
        *   What is the desired behavior from a user's perspective?
        *   How would this feature be used? (e.g., a new button in the UI, a new setting, a change to an existing workflow)
      placeholder: |
        Describe your ideal solution here. For example: "I would like a 'Test Action' button in the Action Editor. When I click it, a panel appears where I can paste some text and see the AI's output immediately, without having to save the action first."
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: 3. Describe Alternatives You've Considered
      description: |
        A clear and concise description of any alternative solutions, features, or workarounds you've considered.
        *   Why were they not suitable?
      placeholder: What other solutions did you think about, and why aren't they a good fit?
    validations:
      required: true

  - type: textarea
    id: ui-mockup
    attributes:
      label: 4. UI Mockup / Design Sketch (if applicable)
      description: If this involves UI changes, a simple sketch, mockup, or screenshot can be very helpful. You can paste images or link to them.
      placeholder: |
        (You can drag and drop images here)
    validations:
      required: false

  - type: textarea
    id: benefits
    attributes:
      label: 5. Benefits
      description: |
        What are the benefits of implementing this feature?
        *   Who would benefit from this? (e.g., all users, prompt engineers, developers)
        *   How would it improve ProseFlow? (e.g., faster workflow, better customization, improved usability)
      placeholder: How would this feature help ProseFlow and its users?
    validations:
      required: true

  - type: textarea
    id: drawbacks-challenges
    attributes:
      label: 6. Potential Drawbacks/Challenges
      description: Are there any potential downsides or implementation challenges you foresee?
      placeholder: Any concerns about implementing this feature? e.g., "This might make the UI too complex," or "This could be difficult to implement on macOS."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 7. Additional Context
      description: Add any other context, examples, or links to relevant resources or similar features in other applications.
      placeholder: Any other relevant information or ideas.
    validations:
      required: false