name: "⏱️ Performance Issue"
description: Report a performance problem with ProseFlow
title: "[PERF] Brief description of the performance issue"
labels: ["performance"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Thank you for reporting a performance issue! Accurate details are key to helping us optimize ProseFlow.**

  - type: checkboxes
    id: requirements-checklist
    attributes:
      label: Requirements Checklist
      options:
        - label: I have searched the existing issues to ensure this performance issue has not already been reported.
          required: true
        - label: I have provided a clear description of the issue and the scenario.
          required: true
        - label: I have included performance metrics if possible (e.g., from the Dashboard or Task Manager).
          required: true
        - label: I have completed the environment information.
          required: true

  - type: textarea
    id: describe-perf-issue
    attributes:
      label: 1. Describe the Performance Issue
      description: |
        A clear and concise description of the performance problem.
        *   Is it high CPU/GPU/RAM usage, slow UI responsiveness, slow model loading, slow text generation, etc.?
      placeholder: Describe the performance problem you are observing.
    validations:
      required: true

  - type: textarea
    id: affected-area
    attributes:
      label: 2. Area of the Application Affected
      description: |
        Which part of ProseFlow seems to be causing the performance issue?
        e.g., Local model inference, Cloud provider requests, the Dashboard, the Floating Orb, the Action Editor.
      placeholder: e.g., Local model text generation is very slow.
    validations:
      required: true

  - type: textarea
    id: scenario
    attributes:
      label: 3. Scenario Causing Slowness
      description: |
        Describe the specific scenario or operations that trigger the performance problem.
        Please provide steps if possible.
      placeholder: |
        e.g., "When I run the 'Summarize' action on a large block of text (approx. 2000 words) using my local model, the application freezes for 10 seconds."
    validations:
      required: true

  - type: textarea
    id: expected-performance
    attributes:
      label: 4. Expected Performance
      description: |
        What level of performance were you expecting in this scenario?
        e.g., "UI should remain responsive", "Local model should generate at least 10 tokens/second", "RAM usage should not exceed 8 GB"
      placeholder: What performance did you expect?
    validations:
      required: true

  - type: textarea
    id: actual-performance
    attributes:
      label: 5. Actual Performance
      description: |
        Describe the observed performance. Provide metrics from the ProseFlow Dashboard or your OS's task manager if possible:
        *   **CPU/GPU Usage:** [e.g., "CPU usage spikes to 100% during generation", "GPU VRAM usage is at 95%"]
        *   **Memory Usage:** [e.g., "Application memory usage grows to 10GB and does not decrease after unloading model"]
        *   **Generation Speed:** [e.g., "Local model only generates 2 tokens/second"]
        *   **UI Responsiveness:** [e.g., "The entire UI freezes when I click 'Load Model'"]
      placeholder: Describe the observed performance and provide metrics if available.
    validations:
      required: true

  - type: textarea
    id: profiling-data
    attributes:
      label: 6. Profiling Data (if available)
      description: |
        If you have run a profiler (e.g., dotTrace, PerfView, Visual Studio Profiler), please share:
        *   Screenshots of hot paths.
        *   Exported profiling sessions (if shareable).
        *   Key findings from the profiler.
      placeholder: Paste profiling data, links, or key findings here.
      render: shell
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### 7. Environment (please complete the following information):

  - type: input
    id: pf-version
    attributes:
      label: ProseFlow Version
      description: e.g., 0.2.0, or commit SHA if building from source.
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: e.g., Windows 11, macOS Sonoma, Ubuntu 22.04
    validations:
      required: true

  - type: input
    id: architecture
    attributes:
      label: Architecture
      description: e.g., x64, ARM64
    validations:
      required: true

  - type: input
    id: hardware-cpu
    attributes:
      label: CPU
      description: e.g., Intel Core i9-13900K, AMD Ryzen 7 7800X3D, Apple M3 Max
    validations:
      required: true

  - type: input
    id: hardware-ram
    attributes:
      label: System RAM
      description: e.g., 16 GB DDR4 3200MHz, 32 GB DDR5 6000MHz
    validations:
      required: true

  - type: input
    id: hardware-gpu
    attributes:
      label: GPU (especially if using Local Provider)
      description: e.g., NVIDIA RTX 4090 (24 GB VRAM), AMD RX 7900 XTX (24 GB VRAM)
    validations:
      required: false

  - type: input
    id: local-model-details
    attributes:
      label: Local Model & Quantization (if relevant)
      description: e.g., ProseFlow-v1-1.5B-Instruct-Q8_0.gguf, Llama-3-8B-Instruct.Q5_K_M.gguf
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 8. Additional Context
      description: |
        Add any other relevant information.
        *   Does the issue get worse with larger input text or more complex actions?
        *   Have you tried different local models or cloud providers?
        *   Have you changed any settings in the Providers page (e.g., thread count, GPU acceleration)?
      placeholder: Any other relevant information.
    validations:
      required: false