name: "💻 Platform-Specific Issue"
description: Report an issue that only occurs on a specific platform or environment
title: "[PLAT] Brief description of the platform-specific issue"
labels: ["bug", "platform-specific"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Thank you for reporting a platform-specific issue! This helps us ensure ProseFlow works well everywhere.**

  - type: checkboxes
    id: requirements-checklist
    attributes:
      label: Requirements Checklist
      options:
        - label: I have searched the existing issues to ensure this platform-specific issue has not already been reported.
          required: true
        - label: I have clearly specified the affected platform(s) and environment details.
          required: true
        - label: I have provided detailed steps to reproduce the issue on the affected platform.
          required: true
        - label: I have indicated if the issue is confirmed to work correctly on other platforms.
          required: true

  - type: markdown
    attributes:
      value: |
        ### 1. Affected Platform(s)
        Please specify the platform(s) where this issue occurs. Be as specific as possible.

  - type: input
    id: os-version
    attributes:
      label: Operating System & Version
      description: e.g., Windows 11 Pro 24H2, macOS Sonoma 14.2, Ubuntu 22.04 LTS
    validations:
      required: true

  - type: input
    id: architecture
    attributes:
      label: Architecture
      description: e.g., x64, ARM64
    validations:
      required: true

  - type: input
    id: window-manager
    attributes:
      label: Window Manager / Desktop Environment (Linux/macOS)
      description: e.g., GNOME (Wayland), KDE Plasma (X11), Aqua
    validations:
      required: false

  - type: input
    id: specific-hardware
    attributes:
      label: Specific Hardware (if relevant)
      description: e.g., Apple M1 Pro, specific keyboard/mouse model, HiDPI display
    validations:
      required: false

  - type: textarea
    id: description-of-issue
    attributes:
      label: 2. Description of the Issue
      description: |
        A clear and concise description of the problem as it manifests on the affected platform(s).
        *   How does the behavior differ from other platforms (if you've tested)?
      placeholder: Describe the issue unique to this platform. e.g., "The global hotkey doesn't work on X11 (Wayland isn't supported yet)," or "The Floating Orb is not transparent on Windows 10."
    validations:
      required: true

  - type: dropdown
    id: works-on-other-platforms
    attributes:
      label: 3. Does it work correctly on other platforms?
      options:
        - "Yes"
        - "No (This might be a general bug, consider the Bug Report template)"
        - "Not Tested / Don't Know"
      default: 2
    validations:
      required: true

  - type: textarea
    id: working-platforms
    attributes:
      label: Which platforms work correctly? (If "Yes" above)
      description: Please specify which platforms you have tested where the issue does *not* occur.
      placeholder: e.g., "Works fine on Windows 11 and Ubuntu 22.04 (X11)."
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 4. Steps to Reproduce (on the affected platform)
      description: Please provide detailed steps to reproduce the behavior *on the affected platform(s)*.
      placeholder: |
        1. On macOS Sonoma, set the Action Menu hotkey to "Cmd+J".
        2. Select text in any application.
        3. Press "Cmd+J".
        4. Observe that the menu does not appear.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 5. Expected Behavior (on the affected platform)
      placeholder: What should happen on this platform?
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: 6. Current Behavior (on the affected platform)
      placeholder: What actually happens on this platform?
    validations:
      required: true

  - type: textarea
    id: error-messages
    attributes:
      label: 7. Error Messages & Logs (if applicable, from the affected platform)
      description: Paste any relevant logs from **About -> Open Log Folder**.
      placeholder: |
        ```
        (Paste full error message and stack trace here)
        ```
      render: shell
    validations:
      required: false

  - type: input
    id: pf-version
    attributes:
      label: 8. ProseFlow Version
      description: e.g., 0.2.0, or commit SHA
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 9. Additional Context
      description: |
        Any other details that might be relevant to this platform-specific issue.
        *   Have you tried any platform-specific configurations or workarounds?
        *   Are you using any accessibility software or other tools that might interfere with keyboard/window events?
      placeholder: Any other relevant information.
    validations:
      required: false