name: "💡 Question"
description: Ask a question about ProseFlow
title: "[QSTN] Your question in a few words"
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Before asking, please ensure your question isn't answered in the [Official Website/Documentation](https://lsxprime.github.io/proseflow-web/) or existing issues.**

  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      options:
        - label: I have searched the documentation and existing issues for an answer.
          required: true
        - label: My question is specific and clearly formulated.
          required: true
        - label: This is not a bug report or a feature request.
          required: true

  - type: textarea
    id: what-trying-to-achieve
    attributes:
      label: 1. What are you trying to achieve?
      description: A clear and concise description of your goal.
      placeholder: Describe your objective or what you're trying to set up. e.g., "I'm trying to create an Action that only appears when I'm using Obsidian."
    validations:
      required: true

  - type: textarea
    id: what-tried-so-far
    attributes:
      label: 2. What have you tried so far?
      description: Please describe the steps you've taken, what you've looked at in the documentation or settings, or any configurations you've experimented with.
      placeholder: "I went to the Action Editor and tried putting 'Obsidian.exe' and 'obsidian' in the 'Application Context' field, but it doesn't seem to be working."
    validations:
      required: true

  - type: textarea
    id: specific-question
    attributes:
      label: 3. What are you unsure about / What is your specific question?
      description: Be precise.
      placeholder: Formulate your exact question here. e.g., "What is the correct format for the Application Context field on macOS? Is it the app name or the bundle identifier?"
    validations:
      required: true

  - type: textarea
    id: relevant-config
    attributes:
      label: 4. Relevant Configuration Snippet (if applicable)
      description: If your question relates to a specific Action or Provider configuration, please include a minimal snippet.
      placeholder: |
        ```json
        // You can export your actions and paste the relevant part here
        "Proofread": {
          "instruction": "...",
          "application_context": ["Obsidian.exe"]
        }
        ```
      render: shell
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### 5. Environment (if relevant to your question):

  - type: input
    id: pf-version
    attributes:
      label: ProseFlow Version
      description: e.g., 0.2.0
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      description: e.g., Windows 11, macOS Sonoma
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 6. Additional Context
      description: Any other information that might help us understand and answer your question.
      placeholder: Provide any extra details here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Important:**
        *   This issue tracker is primarily for bugs and feature requests. For general "how-to" questions, please consider using the [Discussions tab](https://github.com/LSXPrime/ProseFlow/discussions). However, if your question might reveal a documentation gap or an unintuitive aspect of the application, this is the right place.
        *   **This is NOT for reporting bugs or requesting features.** Please use the appropriate templates for those.