name: "🛡️ Security Vulnerability Report"
description: Report a security vulnerability in ProseFlow (Please Read Instructions!)
title: "[SEC] Brief, non-specific description of the potential vulnerability area"
labels: ["security"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **⚠️ IMPORTANT: Reporting Security Vulnerabilities ⚠️**

        Thank you for taking the time to responsibly disclose a potential security vulnerability.

        **To protect our users, please DO NOT report security vulnerabilities through public GitHub issues.**

        Instead, please send a detailed email to: **[lsxprime@gmail.com](mailto:lsxprime@gmail.com)**

        If you are unable to report privately or believe the issue is not sensitive enough to require private disclosure, you may proceed with this template, but be mindful of the information you share publicly.

        **If you are reporting privately via email, please include all the information requested below.**

        ---

        **(Only fill out below if you are certain public disclosure is appropriate or have been asked to do so by a maintainer)**

  - type: checkboxes
    id: responsible-disclosure-ack
    attributes:
      label: Acknowledgement of Responsible Disclosure Policy
      options:
        - label: I understand the importance of responsible disclosure and have considered private reporting first (or this issue is deemed non-sensitive for public view).
          required: true

  - type: input
    id: vulnerability-type
    attributes:
      label: 1. Vulnerability Type
      description: |
        A brief classification of the vulnerability.
        e.g., Information Disclosure, Insecure Deserialization, Path Traversal, Denial of Service (DoS), Unsafe Native Code Invocation
      placeholder: e.g., Information Disclosure (API Keys)
    validations:
      required: false

  - type: textarea
    id: affected-components
    attributes:
      label: 2. Affected Component(s)/Module(s)
      description: |
        Which part(s) of ProseFlow are affected?
        e.g., Workspace Sync, Action Import/Export, Local Provider (GGUF loading), API Key Encryption, UI Markdown Rendering
      placeholder: e.g., Workspace Sync, API Key Encryption
    validations:
      required: false

  - type: textarea
    id: description-of-vulnerability
    attributes:
      label: 3. Description of Vulnerability
      description: |
        A clear and concise description of the vulnerability.
        Explain the weakness and how it can be exploited.
      placeholder: Describe the vulnerability and how it can be exploited.
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 4. Steps to Reproduce (Proof of Concept - PoC)
      description: |
        Provide detailed steps or a configuration snippet (PoC) to demonstrate the vulnerability.
        **Be extremely careful with the PoC you share publicly.** If it's a simple exploit, consider describing it abstractly or waiting for private communication.
      placeholder: |
        1. Create a shared workspace folder.
        2. Craft a malicious `actions.json` file with a payload...
        3. Configure ProseFlow to use this workspace and sync.
        4. Observe the unexpected behavior.
      render: shell
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: 5. Impact
      description: |
        What is the potential impact if this vulnerability is exploited?
        e.g., Application crash, sensitive data leakage (API keys), arbitrary file read/write
      placeholder: Describe the potential impact.
    validations:
      required: false

  - type: textarea
    id: suggested-mitigation
    attributes:
      label: 6. Suggested Mitigation (if known)
      description: If you have an idea on how to fix or mitigate this vulnerability, please share it.
      placeholder: How might this vulnerability be fixed or mitigated?
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### 7. Environment (if specific):

  - type: input
    id: pf-version
    attributes:
      label: ProseFlow Version
      description: e.g., 0.2.0, or commit SHA
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      description: e.g., Windows 11, macOS Sonoma
    validations:
      required: false