namespace ProseFlow.Core.Models;

/// <summary>
/// A record to encapsulate the response from an AI provider, including the content and token usage.
/// </summary>
/// <param name="Content">The text content generated by the AI.</param>
/// <param name="PromptTokens">The number of tokens used in the prompt.</param>
/// <param name="CompletionTokens">The number of tokens generated in the completion.</param>
/// <param name="ProviderName">The name of the AI provider that generated the response (e.g., "OpenAI").</param>
/// <param name="TokensPerSecond">The estimated number of tokens generated per second.</param>
public record AiResponse(string Content, long PromptTokens, long CompletionTokens, string ProviderName, double TokensPerSecond);